name: Diego Alvarez
title: Diego Alvarez (d1egoaz)
tagline: software engineering, emacs enthusiast, golang, rust
description: >-
  software engineering, emacs enthusiast, golang, rust
url: "https://www.diegoa.ca"
github:
  username: d1egoaz
avatar: https://avatars.githubusercontent.com/u/950087?v=4
social:
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Diego Alvarez
  email: diego.canada@icloud.com
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/d1egoaz
    - https://www.linkedin.com/in/d1egoaz

toc: true
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
show_downloads: false
